<SearchWindow>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'basketball.jpg'

    search_by_url: search_by_url
    search_by_name_first: search_by_name_first
    search_by_name_last: search_by_name_last

    RelativeLayout:
        cols: 1
        size: 50, 50
        RelativeLayout:
            Label:
                text: "Timeline of basketball players"
                size_hint: .20, .10
                pos_hint: {'top': 1.0, 'right': .6}
                font_size: '50sp'
                color: 1, .8, .4, .85

        GridLayout:
            cols: 2
            size: 50, 50
            row_force_default: True
            row_default_height: 50
            col_force_default: True
            col_default_width: 600

            Label:

            Label:

            Label:

            Label:

            Label:
                text: "Player first name: "
                bold: True
                font_size: '20sp'

            TextInput:
                id: search_by_name_first
                multilines: False

            Label:

            Label:

            Label:
                text: "Player last name: "
                bold: True
                font_size: '20sp'

            TextInput:
                id: search_by_name_last
                multilines: False

            Label:

            Label:

            Label:

            Label:

            Label:
                text: "Wiki player url: "
                bold: True
                font_size: '20sp'

            TextInput:
                id: search_by_url
                multilines: False

        Button:
            text: "[i]Search![/i]"
            size_hint: .20, .10
            pos_hint: {'top': .3, 'right': .6}
            font_size: '20sp'
            background_color: 1, .3, .4, .85
            markup: True
            border: 25, 25, 25, 25
            bold: True
            on_press: root.btn()

<PlayerScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'basketball2.jpg'
    RelativeLayout:
        cols:1
        size: 50, 50
        RelativeLayout:
            Label:
                text:root.player_name
                bold: True
                markup: True
                size_hint: .20, .10
                pos_hint: {'top': 1.0, 'right': .6}
                font_size: '50sp'
                color: 1, .8, .4, .85

        Label:

        Label:

        RelativeLayout:
            size: 50, 50
            GridLayout:
                cols: 6
                size: 50, 50
                row_force_default: True
                row_default_height: 50
                col_force_default: True
                col_default_width: 200

                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:
                Label:

                Label:
                Label:
                    text: "Born in: "
                    bold: True
                    font_size: '30sp'


                Label:
                    text: root.born_place
                    font_size: '20sp'


                Label:
                Label:
                Label:

                Label:
                Label:
                Label:
                Label:
                Label:
                Label:

                Label:
                Label:
                    text: "Birth Date: "
                    bold: True
                    font_size: '30sp'


                Label:
                    text: root.born_date
                    font_size: '20sp'

                Label:
                Label:
                Label:

                Label:
                Label:
                Label:
                Label:
                Label:
                Label:

                Label:
                Label:
                    text: "High School: "
                    bold: True
                    font_size: '30sp'


                Label:
                    text: root.high_school
                    font_size: '20sp'

                Label:
                Label:
                Label:

                Label:
                Label:
                Label:
                Label:
                Label:
                Label:

                Label:
                Label:
                    text: "College: "
                    bold: True
                    font_size: '30sp'

                Label:
                    text: root.college
                    font_size: '20sp'

                Label:
                Label:
                Label:








            AsyncImage:
                source: root.photo_url
                size: self.texture_size
                pos_hint: {'top': 1.07,'right': 1.2}


            Button:
                text: "[i]To player Time Line![/i]"
                size_hint: .20, .10
                pos_hint: {'top': .2, 'right': .78}
                font_size: '20sp'
                background_color:1, .8, .4, .85
                markup: True
                background_normal: 'normal.png'
                background_down: 'down.png'
                border: 30, 30, 30, 30
                bold: True
                on_press: root.manager.current = 'time_line'

            Button:
                text: "[i]Back to search window![/i]"
                size_hint: .20, .1
                pos_hint: {'top': .2, 'right': .38}
                font_size: '20sp'
                background_color: 1, .8, .4, .85
                markup: True

                background_normal: 'normal.png'
                background_down: 'down.png'
                border: 30, 30, 30, 30
                bold: True
                on_press:  root.manager.current = 'search'



<LineEllipse1>:
    Label:
        center: root.center
        text: 'Ellipse'


<TimeLineScreen>:
    canvas.before:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'basketball2.jpg'


    RelativeLayout:
        cols:1
        RelativeLayout:
        Label:
            text: root.player_name
            bold: True
            markup: True
            size_hint: .20, .10
            pos_hint: {'top': 1.0, 'right': .47}
            font_size: '50sp'
            color: 1, .8, .4, .85

        Label:
            text: "TimeLine"
            bold: True
            markup: True
            size_hint: .20, .10
            pos_hint: {'top': 1.0, 'right': .7}
            font_size: '50sp'
            color: 1, .8, .4, .85

        Label:
            text: "Year: "
            bold: True
            markup: True
            size_hint: .20, .10
            pos_hint: {'top': .8, 'right': .2}
            font_size: '50sp'
            color: 1, .8, .4, .85


        Label:
            text:root.curr_year
            bold: True
            markup: True
            size_hint: .20, .10
            pos_hint: {'top': .8, 'right': .3}
            font_size: '50sp'
            color: 1, .8, .4, .85




        GridLayout:
            id: grid
            cols: 1
            size_hint_y: 0.85



        GridLayout:
            cols: 2
            size_hint_y: 0.10
            # row_force_default: True
            # height: 40

            Button:
                text: root.prev_year
                size_hint: .20, .10
                pos_hint: {'top': .3, 'right': .6}
                font_size: '20sp'
                background_color: 1, .3, .4, .85
                markup: True
                bold: True
                on_press: root.prev_btn()

            Button:
                text: root.next_year
                size_hint: .20, .10
                pos_hint: {'top': .3, 'right': .6}
                font_size: '20sp'
                background_color: 1, .3, .4, .85
                markup: True
                bold: True
                on_press: root.next_btn()
        Button:
            text: "[i]Back to search window![/i]"
            size_hint: .20, .10
            pos_hint: {'top': .3, 'right': .6}
            font_size: '20sp'
            background_color: 1, .3, .4, .85
            markup: True
            bold: True
            on_press:  root.manager.current = 'search'


